// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOS7_v-jexutrSal1f_KkxFLFXn2zgBag',
    appId: '1:781442616179:web:fe883d9a4e270d1b649306',
    messagingSenderId: '781442616179',
    projectId: 'test-a43ec',
    authDomain: 'test-a43ec.firebaseapp.com',
    storageBucket: 'test-a43ec.firebasestorage.app',
    measurementId: 'G-HQK0DGH51E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTS79VsmNW8knHXBAYE50emJ1AMmf6Fw',
    appId: '1:781442616179:android:101c650d09b56897649306',
    messagingSenderId: '781442616179',
    projectId: 'test-a43ec',
    storageBucket: 'test-a43ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-8ngNkx1s5fEXHj6rpTiO8JHKYqoyBeE',
    appId: '1:781442616179:ios:17c2e493a526d1f9649306',
    messagingSenderId: '781442616179',
    projectId: 'test-a43ec',
    storageBucket: 'test-a43ec.firebasestorage.app',
    iosBundleId: 'com.example.beitiCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-8ngNkx1s5fEXHj6rpTiO8JHKYqoyBeE',
    appId: '1:781442616179:ios:17c2e493a526d1f9649306',
    messagingSenderId: '781442616179',
    projectId: 'test-a43ec',
    storageBucket: 'test-a43ec.firebasestorage.app',
    iosBundleId: 'com.example.beitiCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOS7_v-jexutrSal1f_KkxFLFXn2zgBag',
    appId: '1:781442616179:web:422028feb25ee022649306',
    messagingSenderId: '781442616179',
    projectId: 'test-a43ec',
    authDomain: 'test-a43ec.firebaseapp.com',
    storageBucket: 'test-a43ec.firebasestorage.app',
    measurementId: 'G-BK7QXM9960',
  );
}
